### ISSUE TITLE
Incorrect GS1 barcode

### ISSUE THREAD

**Issue by lorenzocostalunga** [mak3e/Barcode128#1]
Ciao,
returns an incorrect barcode when multiple AI codes are used.

Example:
var s = Code128.StringToBarcode("(02)08003625100263(10)L1706199(37)120");
Barcode resulting:
020800362510026310L1706199E,0

var s = BarcodeX.Code128.StringToBarcode("(02)08003625100263(37)120(10)L1706199");
Barcode resulting:
020800362510026337120(L1706199

**Comment by mak3e** [comment]
Yeah, sorry, the original use case needed support for only one AI code, but I can take a look at it.

**Comment by mak3e** [comment]
I was able to reproduce the issue, I will commit asap if I find a solution!

**Comment by mak3e** [comment]
I rewrote the library on my spare time during weekend! This issue is now fixed.

Happy Barcoding!
-Make
